// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: GUI_copy

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3B5108), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 220);
lv_obj_set_height( ui_TextArea1, 110);
lv_obj_set_x( ui_TextArea1, 0 );
lv_obj_set_y( ui_TextArea1, 240 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TextArea1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TextArea1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
lv_textarea_set_text(ui_TextArea1,"TESTER");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xBEF874), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_TextArea2 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea2, 220);
lv_obj_set_height( ui_TextArea2, 220);
lv_obj_set_x( ui_TextArea2, 0 );
lv_obj_set_y( ui_TextArea2, 10 );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TextArea2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TextArea2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
lv_textarea_set_text(ui_TextArea2,"TESTER");
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0xBEF874), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_TextArea2, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea3, 220);
lv_obj_set_height( ui_TextArea3, 60);
lv_obj_set_x( ui_TextArea3, 0 );
lv_obj_set_y( ui_TextArea3, 360 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TextArea3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TextArea3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
lv_textarea_set_text(ui_TextArea3,"TESTER");
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0xBEF874), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_TextArea3, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_TextArea4 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea4, 220);
lv_obj_set_height( ui_TextArea4, 95);
lv_obj_set_x( ui_TextArea4, 0 );
lv_obj_set_y( ui_TextArea4, 430 );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TextArea4,LV_FLEX_FLOW_ROW_REVERSE);
lv_obj_set_flex_align(ui_TextArea4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
lv_textarea_set_text(ui_TextArea4,"TESTER");
lv_textarea_set_placeholder_text(ui_TextArea4,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0xBEF874), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0x0A0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_TextArea4, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

}
